### ISSUE TITLE
Feature request: Scan packages from external project

### ISSUE THREAD

**Issue by Incognito** [seddonym/grimp#82]
I have a project where I want to scan a target directory of another project that is not in the project grimp is installed in. I was reading through the code and it appears to be possible as the import graph is determined by AST parsing of files in a directory. Has a feature like this been considered or even seen as desirable to have (in the scope of grimp's goals)?

I was thinking a lot could be possible if we changed some behaviour inside `def build_graph(` https://github.com/seddonym/grimp/blob/8b4e33a370e5922887c69cbea4c3423fa89943b1/src/grimp/application/usecases.py#L15 or provided a different "usecase" that is filesystem based for the parameter. What do you think?

**Comment by seddonym** [comment]
Hi Brian, thanks for the question!

> I want to scan a target directory of another project that is not in the project grimp is installed in

If I'm understanding correctly, this is the normal way of using Grimp. It allows you to scan any Python package providing it's importable (i.e. in the Python path). You can also analyse [multiple packages in the same graph](https://grimp.readthedocs.io/en/stable/readme.html#multiple-packages).

The `AbstractFileSystem` in the source code is purely a coding pattern for 'coding to an interface, not an implementation'. It allows us to write [expressive unit tests by using an in-memory test double of the file system](https://github.com/seddonym/grimp/blob/8b4e33a370e5922887c69cbea4c3423fa89943b1/tests/unit/application/test_usecases.py#L12) so we can express all the logic within the test, rather than needing to create real files to read.

Does that help? Let me know if I've misunderstood, otherwise I'll close the issue.

**Comment by Incognito** [comment]
Hey thanks for the response, I think the part I didn't make clear is I want to have two different python projects and when I use grimp the API assumes that all the modules loaded are "in the project" already.

For example, I must do:

```python
import grimp
graph = grimp.build_graph('somepackage')
```

But what I want is:

```python
# /home/brian/projects/static-graph-analysis.py

import grimp
graphs = [
    grimp.build_graph_from_path('/home/brian/projects/coca-cola-cost-calculator'),
    grimp.build_graph_from_path('/home/brian/projects/tesla-sales-page'),
    grimp.build_graph_from_path('/home/brian/projects/airbus-landing-page'),
    grimp.build_graph_from_path('/home/brian/projects/enron-financial-systems'),
]
```
The projects are all unrelated and should be statically analysed without needing to be in the pypath of where I start grimp. I don't want any modules from coca-cola, tesla. airbus, etc loaded into `python`, but I do want grimp to parse those files and build the import graph.

**Comment by Incognito** [comment]
Might be a silly question but I looked into Impulse too, is what I'm looking for as simple as this?

```
def build_graph(path, module):
    sys.path.insert(0, path)
    module = grimp.Module(module)
    graph = grimp.build_graph(module.package_name)
```

**Comment by seddonym** [comment]
Hi Brian - sorry for delay in replying.

I'm having trouble understanding what problem you're running into - that you can't build multiple graphs, or that you specifically want to build the graphs from a directories rather than package names?

Is there any reason you can't do this:

```
import grimp
graphs = [
    grimp.build_graph_from_path('coca-cola-cost-calculator'),
    grimp.build_graph_from_path('tesla-sales-page'),
    grimp.build_graph_from_path('airbus-landing-page'),
    grimp.build_graph_from_path('enron-financial-systems'),
]
```
(If they're not on the Python path, then there are a few ways to do this but I'm assuming you're familiar with how to do that?)

Re. Impulse: this is just a thin wrapper around Grimp that renders a particular part of the graph as an image.

**Comment by Incognito** [comment]
Hey, the main reason I can't do what your example proposes is because all of these are distinct python projects. They don't share git repos, for example. Every project in my example under `/home/brian/projects` belongs to a different company and I would be forbidden from sharing one big project with all of them.

**Comment by seddonym** [comment]
I'm still not clear what the problem is - maybe it would be easier to have a verbal conversation sometime? Feel free to reach out on david@seddonym.me and we can have a chat if you like?

**Comment by Incognito** [comment]
Just for future reference or if anyone has similar needs, I've made a basic implementation here that replaces the "scanning" part of grimp but re-uses all the other parts.

https://github.com/Incognito/python-architecture-linter/tree/main/python_architecture_linter_grimp_extension

I solved it by pre-computing the module name of a file relative to the place in a project and normalising all module paths using astroid's normaliser:

https://github.com/Incognito/python-architecture-linter/blob/b3cf41433c40fdd873ebdd92bf1f7784b905b147/python_architecture_linter/node_navigators.py#L38-L46

https://github.com/Incognito/python-architecture-linter/blob/b3cf41433c40fdd873ebdd92bf1f7784b905b147/python_architecture_linter_grimp_extension/node_normaliser.py#L18
